# PG Tables

## PG x- vs x+

```{r, echo=FALSE, strip.white=FALSE, results="asis"}
for(i in c("all", "antiNSAIDS","inflamOrRheum", "earlierdep", "caesarean")){
  tab <- readRDS(paste0("results/supplemental_IFsummariesTable_",i,".RDS"))
  cat("### ",i,"\n")
  cat("\n")
  cat(tab[["PG x- vs x+"]])
  cat("\n")
  
}
```

## PG -- vs -+

```{r, echo=FALSE, strip.white=FALSE, results="asis"}
for(i in c("all", "antiNSAIDS","inflamOrRheum", "earlierdep", "caesarean")){
   tab <- readRDS(paste0("results/supplemental_IFsummariesTable_",i,".RDS"))
  cat("### ",i,"\n")
  cat("\n")
  cat(tab[["PG -- vs -+"]])
  cat("\n")
}
```


# PP Tables

## PP x- vs x+

```{r, echo=FALSE, strip.white=FALSE, results="asis"}
for(i in c("all", "antiNSAIDS","inflamOrRheum", "earlierdep", "caesarean")){
  tab <- readRDS(paste0("results/supplemental_IFsummariesTable_",i,".RDS"))
  cat("### ",i,"\n")
  cat("\n")
  cat(tab[["PP x- vs x+"]])
  cat("\n")
}
```

## PP -- vs -+

```{r, echo=FALSE, strip.white=FALSE, results="asis"}
for(i in c("all", "antiNSAIDS","inflamOrRheum", "earlierdep", "caesarean")){
 tab <- readRDS(paste0("results/supplemental_IFsummariesTable_",i,".RDS"))
  cat("### ",i,"\n")
  cat("\n")
  cat(tab[["PP -- vs -+"]])
  cat("\n")
}
```